export const MAIL_ERROR_CODES = [
  'MAIL_CONFIG_DISABLED',
  'MAIL_SMTP_UNREACHABLE',
  'MAIL_SMTP_AUTH_FAILED',
  'MAIL_SMTP_TLS_FAILED',
  'MAIL_SMTP_RECIPIENT_REJECTED',
  'MAIL_SMTP_RATE_LIMITED',
  'MAIL_SMTP_TRANSIENT',
  'MAIL_PAYLOAD_INVALID',
  'MAIL_TEMPLATE_UNSUPPORTED',
  'MAIL_CREDENTIAL_INVALID',
  'MAIL_ATTEMPTS_EXHAUSTED',
  'SMTP_DELIVERY_UNKNOWN',
] as const;

export type MailErrorCode = (typeof MAIL_ERROR_CODES)[number];
