export const configuration = () => ({
  app: {
    environment: process.env.NODE_ENV ?? 'development',
    port: Number(process.env.PORT ?? 4000),
    version: process.env.APP_VERSION ?? '0.1.0',
    frontendOrigins: process.env.FRONTEND_ORIGINS ?? 'http://localhost:3000',
    cookieSecure: process.env.COOKIE_SECURE === 'true',
    mfaTotpIssuer: process.env.MFA_TOTP_ISSUER ?? 'DanangMap',
    trustProxyHops: Number(process.env.TRUST_PROXY_HOPS ?? 0),
  },
  redis: {
    host: process.env.REDIS_HOST ?? 'localhost',
    port: Number(process.env.REDIS_PORT ?? 6379),
    password: process.env.REDIS_PASSWORD || undefined,
  },
  minio: {
    endpoint: process.env.MINIO_ENDPOINT ?? 'localhost',
    port: Number(process.env.MINIO_PORT ?? 9000),
    useSsl: process.env.MINIO_USE_SSL === 'true',
    accessKey: process.env.MINIO_ACCESS_KEY,
    secretKey: process.env.MINIO_SECRET_KEY,
    bucket: process.env.MINIO_BUCKET ?? 'danangmap',
  },
  geoService: {
    baseUrl: process.env.GEO_SERVICE_BASE_URL ?? '',
    authHeader: process.env.GEO_SERVICE_AUTH_HEADER || undefined,
    connectTimeoutMs: Number(process.env.GEO_SERVICE_CONNECT_TIMEOUT_MS ?? 2_000),
    totalTimeoutMs: Number(process.env.GEO_SERVICE_TOTAL_TIMEOUT_MS ?? 5_000),
    retryAttempts: Number(process.env.GEO_SERVICE_RETRY_ATTEMPTS ?? 2),
    retryDelayMs: Number(process.env.GEO_SERVICE_RETRY_DELAY_MS ?? 100),
    breakerFailureThreshold: Number(process.env.GEO_SERVICE_BREAKER_FAILURE_THRESHOLD ?? 5),
    breakerOpenMs: Number(process.env.GEO_SERVICE_BREAKER_OPEN_MS ?? 30_000),
  },
  mail: {
    enabled: process.env.SMTP_ENABLED === 'true',
    required: process.env.MAIL_DELIVERY_REQUIRED === 'true',
    smtp: {
      host: process.env.SMTP_HOST || undefined,
      port: Number(process.env.SMTP_PORT ?? 587),
      tlsMode: process.env.SMTP_TLS_MODE ?? 'starttls',
      rejectUnauthorized: process.env.SMTP_REJECT_UNAUTHORIZED !== 'false',
      username: process.env.SMTP_USERNAME || undefined,
      password: process.env.SMTP_PASSWORD || undefined,
      fromName: process.env.SMTP_FROM_NAME ?? 'DanangMap',
      fromAddress: process.env.SMTP_FROM_ADDRESS || undefined,
      replyToAddress: process.env.SMTP_REPLY_TO_ADDRESS || undefined,
      connectionTimeoutMs: Number(process.env.SMTP_CONNECTION_TIMEOUT_MS ?? 5_000),
      greetingTimeoutMs: Number(process.env.SMTP_GREETING_TIMEOUT_MS ?? 5_000),
      socketTimeoutMs: Number(process.env.SMTP_SOCKET_TIMEOUT_MS ?? 15_000),
      maxConnections: Number(process.env.SMTP_POOL_MAX_CONNECTIONS ?? 2),
      rateLimitPerMinute: Number(process.env.SMTP_RATE_LIMIT_PER_MINUTE ?? 60),
    },
    perRecipientIntervalSeconds: Number(process.env.SMTP_PER_RECIPIENT_INTERVAL_SECONDS ?? 60),
    sweepIntervalMs: Number(process.env.MAIL_SWEEP_INTERVAL_MS ?? 5_000),
    smtpProbeIntervalMs: Number(process.env.SMTP_PROBE_INTERVAL_MS ?? 30_000),
    claimLeaseSeconds: Number(process.env.MAIL_CLAIM_LEASE_SECONDS ?? 60),
    maxAttempts: Number(process.env.MAIL_MAX_ATTEMPTS ?? 5),
    backoffBaseSeconds: Number(process.env.MAIL_BACKOFF_BASE_SECONDS ?? 30),
    backoffMaxSeconds: Number(process.env.MAIL_BACKOFF_MAX_SECONDS ?? 3_600),
    backoffJitterPercent: Number(process.env.MAIL_BACKOFF_JITTER_PERCENT ?? 20),
    failedPayloadRetentionHours: Number(process.env.MAIL_FAILED_PAYLOAD_RETENTION_HOURS ?? 24),
    workerHeartbeatStaleSeconds: Number(process.env.MAIL_WORKER_HEARTBEAT_STALE_SECONDS ?? 120),
  },
});
